; This script auto-generated by DEPLOY.BAT 
#define MyAppVersion "1.1.0-beta-1"
#define MyReleaseStatus "beta"
#define MyBuildNumber "200"
#define MyVersionNumbers "1.1.0.200"
#define MyGitBranch "translations"
#define MyGitRevision "8e2b0e0c-plus"
#define MySuffix ""  
